### ISSUE TITLE
While executing npm run build

### ISSUE THREAD

**Issue by SanthoshDhandapani** [paulsevere/react-electron-scripts#1]
\node_modules\react-electron-scripts\config\
webpack.config.prod.js:223
          )
          ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by paulsevere** [comment]
Oops, older node versions can't handle the trailing commas.  I published a fixed version.

**Comment by SanthoshDhandapani** [comment]
Hi Paul,
Thanks for your quick response, now the npm run build works fine.  While installing i faced another issue, though i already installed electron globally, i hit no during installation process where below error is thrown 

\node_modules\react-electron-scripts\scr
ts\init.js:15
  throw err;
  ^
null

As a result, no application is created. You can open this as a separate issue.

**Comment by paulsevere** [comment]
I think it should work now

**Comment by SanthoshDhandapani** [comment]
Yeah, working fine. Thanks paul.

**Comment by paulsevere** [comment]
No problem.  I think this is the first time anyone has ever actually used something I made, so this is exciting.

**Comment by SanthoshDhandapani** [comment]
If you complete your todo, i hope more people will use this to generate their electron app.
